name: Android CI

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Use cache for Gradle'
        required: true
        type: boolean
        default: true

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.11.1"

      - name: Set Commit Hash
        id: commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build Debug APK
        run: gradle assembleDebug --no-daemon

      - name: Archive APK Artifact
        uses: actions/upload-artifact@v7
        with:
          name: AndroidViewDownloads-${{ env.COMMIT_HASH }}
          path: app/build/outputs/apk/debug/*.apk
